import express, { Request, Response } from "express";
import path from "path";
import { GoogleGenAI } from "@google/genai";
import dotenv from "dotenv";

dotenv.config();

// Initialize Gemini API Client
const ai = new GoogleGenAI({
  apiKey: process.env.GEMINI_API_KEY,
  httpOptions: {
    headers: {
      'User-Agent': 'aistudio-build',
    }
  }
});

async function startServer() {
  const app = express();
  const PORT = 3000;

  // Middleware for JSON parsing
  app.use(express.json({ limit: '10mb' }));

  // API Route: Generate Retro Sprite via Imagen
  app.post("/api/generate-sprite", async (req: Request, res: Response) => {
    try {
      const { prompt, style, pose, bgColor } = req.body;

      if (!prompt) {
        return res.status(400).json({ error: "Prompt is required" });
      }

      // Check for Gemini API key
      if (!process.env.GEMINI_API_KEY) {
        return res.status(500).json({ 
          error: "GEMINI_API_KEY is not configured. Please add it in Settings > Secrets." 
        });
      }

      // Construct a tailored prompt for high-quality pixel-art sprites
      let styleDescriptor = "";
      if (style === "snes") {
        styleDescriptor = "Super NES (SNES) 16-bit console aesthetic, vibrant color palette, nostalgic warm tones";
      } else if (style === "genesis") {
        styleDescriptor = "Sega Mega Drive (Sega Genesis) 16-bit retro style, high contrast, dark gritty tones, metallic synthwave aesthetic";
      } else {
        styleDescriptor = "16-bit retro arcade game style, retro pixel art, clean colors";
      }

      const poseText = pose ? `in a clear side-view/profile ${pose} pose` : "in a clear side-view stance";

      // Formulate a solid background description for easy transparency chroma keying
      let bgDesc = "";
      if (bgColor === "magenta") {
        bgDesc = "a solid, completely flat, uniform pure bright magenta background (hex #FF00FF)";
      } else if (bgColor === "green") {
        bgDesc = "a solid, completely flat, uniform pure bright green background (hex #00FF00)";
      } else if (bgColor === "blue") {
        bgDesc = "a solid, completely flat, uniform pure bright blue background (hex #0000FF)";
      } else if (bgColor === "black") {
        bgDesc = "a solid, completely flat, uniform pure black background (hex #000000)";
      } else if (bgColor === "white") {
        bgDesc = "a solid, completely flat, uniform pure white background (hex #FFFFFF)";
      } else {
        bgDesc = "a solid, completely flat, uniform pure neutral gray background (hex #808080)";
      }

      const fullPrompt = `Pixel art character sprite of ${prompt}, ${poseText}. 
${styleDescriptor}.
The character must be isolated and centered in the frame.
Must have ${bgDesc}. 
No gradients, no shading or shadows on the background, completely flat background color. 
16-bit, sharp clean pixels, retro video game asset, side scroller platformer style.`;

      console.log(`Generating sprite using model 'gemini-2.5-flash-image' with prompt:\n"${fullPrompt}"`);

      // Call Gemini 2.5 Flash Image via the Google Gen AI SDK
      const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: {
          parts: [
            {
              text: fullPrompt,
            },
          ],
        },
        config: {
          imageConfig: {
            aspectRatio: '1:1',
          },
        },
      });

      let base64EncodeString = "";
      if (response.candidates?.[0]?.content?.parts) {
        for (const part of response.candidates[0].content.parts) {
          if (part.inlineData) {
            base64EncodeString = part.inlineData.data;
            break;
          }
        }
      }

      if (!base64EncodeString) {
        throw new Error("No images were generated by the model. Response text: " + (response.text || "Empty response"));
      }

      const imageUrl = `data:image/png;base64,${base64EncodeString}`;

      return res.json({ 
        success: true, 
        imageUrl,
        prompt: fullPrompt 
      });

    } catch (error: any) {
      console.error("Error generating sprite:", error);
      return res.status(500).json({ 
        error: error.message || "An error occurred while generating the retro sprite image." 
      });
    }
  });

  // Vite Integration for Dev / Prod serving
  if (process.env.NODE_ENV !== "production") {
    const { createServer: createViteServer } = await import("vite");
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req: Request, res: Response) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Express server running on http://0.0.0.0:${PORT} in ${process.env.NODE_ENV || 'development'} mode`);
  });
}

startServer().catch((err) => {
  console.error("Failed to start full-stack server:", err);
});
